### ISSUE TITLE
Encourage community involvement

### ISSUE THREAD

**Issue by maorfr** [AmboVent/AmboVent#15]
Hello folks,

First and foremost - THANK YOU!!

As this repository is open source, it will be amazing to encourage the open source community to get involved in the work being done.

A good way to get help is to create issues stating what help is needed. To each such issue, you can add the `help-wanted` label.

There are many who would like to help! Help us help you!

Thank you again. This project is TRULLY a life saver.

**Comment by MatanYemini** [comment]
Waiting for you to add more issues, or just share what is planned:)

**Comment by nimrod46** [comment]
Thank you! We will keep that in mind, for now, I will close the issue.
Feel free to open PR as you feel the need to improve things
