### ISSUE TITLE
It seems like you're closing issues too soon

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [AmboVent/AmboVent#24]
Hi @nimrod46, I notice you seem to be giving me the go-ahead/approval to work on issue #21, yet you've closed it. In normal workflows issues are only closed if they are either 1) fully implemented and complete, or 2) rejected and never going to be fixed. Since I haven't implemented #21, that means you are rejecting it, but I don't think that's your intention. If that's not your intention, please open it until it's fully implemented. What you can do, however, is add a label which says "in-work" or whatever the best label is, and assign it to me if you make me a collaborator.

The same goes for #22. You've closed it, yet it is not implemented, and you seem to not be intending to reject it based on your words there.

Same with #19. You've closed it yet the Low memory problem isn't fully fixed, and I think it still could be fully fixed (although @giorakor did make it much better and partially fix it I'd still leave it open). 

Also #11 still has a lot of work left to be done so I recommend leaving it open for me to work on.

I suspect this is the case with most other closed issues as well, so keep in mind if you close them it communicates to others they are either fixed, or rejected because they're never going to be fixed. 

Thanks!

This issue, for instance: if you close it without further comment, it either communicates: 1) "I, @nimrod46, don't agree with you and I'm not going to make the changes you're requesting", or 2) "I just did everything you recommended and it is now totally fixed": ie: "I've re-opened all of those issues."

**Comment by nimrod46** [comment]
Sorry for the misunderstanding, wanted to keep the issues here clean but I guess that the right labels will do the work.
I reopened the issues you mentioned if there are more tell me and I will reopen them as well.
